SOURCE: 'Unity'
TARGET: 'Real'

TRAIN:
  DA_METHOD: AdvEnt
  MODEL: DeepLabv2
  RESTORE_FROM: pretrained_models/DeepLab_resnet_pretrained_imagenet.pth
  MULTI_LEVEL: True
  LAMBDA_ADV_MAIN: 0.001
  LAMBDA_ADV_AUX: 0.0002
  MAX_ITERS:
    250000
  EARLY_STOP:
    200000
TEST:
  MODE: best
  
data:
  loaders:
    batch_size: 40 # 40, max=93
    shuffle: True
    num_workers: 8