SOURCE: 'Unity'
TARGET: 'Real'

TRAIN:
  DA_METHOD: AdvEnt
  MODEL: DeepLabv2
  RESTORE_FROM: pretrained_models/DeepLab_resnet_pretrained_imagenet.pth
  MULTI_LEVEL: True
  LAMBDA_ADV_MAIN: 0.001
  LAMBDA_ADV_AUX: 0.0002
  MAX_ITERS:
    250000
  EARLY_STOP:
    200000
  checkpoint_iter:
    36000
  SNAPSHOT_DIR:
    '/network/tmp1/ccai/checkpoints/tianyu/advent-continue_v1'
    
TEST:
  MODE: best
  isShowcomet_ml:
    True
  Model:
    test_iter:
      36000
    save_pred_path_default:
      True
    save_pred_path_customized:
      ""
  
data:
  use_real: true
  files: # if one is not none it will override the dirs location
    base: "/network/tmp1/ccai/data/mask_generation/Unity11K+8800_lowRes_full_train" # ! Check output_dir
    train: train.json
    val: test.json

  real_files:
    base: "/network/tmp1/ccai/data/mask_generation/real"
    train: train.json
    val: val_Cityscapes.json
    
  loaders:
    batch_size: 40 # 40, max=93
    shuffle: True
    num_workers: 8
   
  transforms:
    - name: hflip
      ignore: true
      p: 0.5
    - name: resize
      ignore: false
      new_size: 256 #! Make sure this matches opts.data.img_size
    - name: crop
      ignore: true
      height: 224
      width: 224
    - name: resize # ? this or change generator's output? Or resize larger then crop to 256?
      ignore: false
      new_size: 256 #! Make sure this matches opts.data.img_size